[versions]
androidPluginVersion = "8.11.1"
annotation = "1.9.1"
kspPluginVersion = "2.2.0-2.0.2"
kotlinVersion = "2.2.0"
kotlinCoroutinesVersion = "1.10.2"
constraintlayout = "2.2.1"
media3 = "1.8.0"
cardview = "1.0.0"
appcompat = "1.7.1"
coreSplashscreen = "1.0.1"
coreVersion = "1.17.0"
fragmentKtx = "1.8.9"
libphonenumberAndroid = "9.0.17"
lifecycleVersion = "2.9.4"
loader = "1.1.0"
material = "1.13.0"
navigationVersion = "2.9.5"
preferenceKtx = "1.2.1"
prettytime = "5.0.4.Final"
recyclerview = "1.4.0"
roomVersion = "2.8.3"
koinVersion = "4.1.1"
swiperefreshlayout = "1.1.0"
advrecyclerview = "1.0.0"
coilVersion = "3.3.0"
versioncompare = "1.5.0"
viewpager2 = "1.1.0"
markdown = "4.6.2"
photoviewVersion = "1.0.3"
ktor = "3.3.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-loader = { module = "androidx.loader:loader", version.ref = "loader" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreVersion" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3" }
androidx-media3-effect = { module = "androidx.media3:media3-effect", version.ref = "media3" }
material-components = { module = "com.google.android.material:material", version.ref = "material" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutinesVersion" }

lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleVersion" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationVersion" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationVersion" }

photoview = { module = "io.getstream:photoview", version.ref = "photoviewVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinVersion" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coilVersion" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coilVersion" }

advrecyclerview = { module = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview", version.ref = "advrecyclerview" }
libphonenumber = { module = "io.michaelrocks:libphonenumber-android", version.ref = "libphonenumberAndroid" }
prettytime = { module = "org.ocpsoft.prettytime:prettytime", version.ref = "prettytime" }
versioncompare = { module = "io.github.g00fy2:versioncompare", version.ref = "versioncompare" }

markdown-core = { module = "io.noties.markwon:core", version.ref = "markdown" }
markdown-html = { module = "io.noties.markwon:html", version.ref = "markdown" }

[bundles]
ktor = ["ktor-client-core", "ktor-client-okhttp", "ktor-serialization-json", "ktor-client-content-negotiation", "ktor-client-encoding"]
media3 = ["androidx-media3-exoplayer", "androidx-media3-transformer", "androidx-media3-ui", "androidx-media3-effect"]

[plugins]
agp = { id = "com.android.application", version.ref = "androidPluginVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "kspPluginVersion" }
androidx-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigationVersion" }