[versions]
agp = "8.11.1"
ksp = "2.2.0-2.0.2"
kotlin = "2.2.0"

kotlinDatetime = "0.7.1"
kotlinCoroutines = "1.10.2"
material = "1.13.0"
core = "1.17.0"
coreSplashscreen = "1.0.1"
appcompat = "1.7.1"
fragment = "1.8.9"
media3 = "1.8.0"
documentfile = "1.1.0"
preference = "1.2.1"
constraintlayout = "2.2.1"
swiperefreshlayout = "1.1.0"
recyclerview = "1.4.0"
cardview = "1.0.0"
viewpager2 = "1.0.0"
lifecycle = "2.9.4"
room = "2.8.2"
navigation = "2.9.5"

koin = "4.1.1"
coil = "3.3.0"
ktor = "3.3.1"

markwon = "4.6.2"
advrecyclerview = "1.0.0"
photoview = "1.0.3"
versioncompare = "1.5.0"
libphonenumberAndroid = "9.0.17"
prettytime = "5.0.4.Final"

[libraries]
material-components = { module = "com.google.android.material:material", version.ref = "material" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }

lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }

room = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

navigation-common = { module = "androidx.navigation:navigation-common-ktx", version.ref = "navigation" }
navigation-runtime = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon-html = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }

advrecyclerview = { module = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview", version.ref = "advrecyclerview" }
photoview = { module = "io.getstream:photoview", version.ref = "photoview" }

versioncompare = { module = "io.github.g00fy2:versioncompare", version.ref = "versioncompare" }
libphonenumber = { module = "io.michaelrocks:libphonenumber-android", version.ref = "libphonenumberAndroid" }
prettytime = { module = "org.ocpsoft.prettytime:prettytime", version.ref = "prettytime" }

[bundles]
kotlinx = ["kotlinx-datetime", "kotlinx-coroutines-android"]
lifecycle = ["lifecycle-common", "lifecycle-runtime", "lifecycle-livedata", "lifecycle-viewmodel"]
media3 = ["media3-exoplayer", "media3-ui"]
navigation = ["navigation-common", "navigation-runtime", "navigation-fragment", "navigation-ui"]
koin = ["koin-core", "koin-android"]
coil = ["coil", "coil-video"]
ktor = ["ktor-client-core", "ktor-client-okhttp", "ktor-serialization-json", "ktor-client-content-negotiation", "ktor-client-encoding"]
markwon = ["markwon-core", "markwon-html", "markwon-linkify"]

[plugins]
android = { id = "com.android.application", version.ref = "agp" }
android-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }